# Generated by Django 5.2.6 on 2025-09-29 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del producto', max_length=500)),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio del producto', max_digits=10)),
                ('url', models.URLField(help_text='URL única del producto para evitar duplicados', unique=True)),
                ('image', models.URLField(blank=True, help_text='URL de la imagen del producto', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación')),
                ('shipping_time', models.PositiveIntegerField(blank=True, help_text='Tiempo de envío en días', null=True)),
                ('category', models.CharField(blank=True, help_text='Categoría del producto', max_length=200, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Calificación del producto (0.00 - 5.00)', max_digits=3, null=True)),
                ('source_platform', models.CharField(default='aliexpress', help_text='Plataforma de origen del producto', max_length=100)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
    ]
